services:
  nggasak-analyzer:
    build: .
    container_name: nggasak-analysis
    user: "nggasak"
    volumes:
      - ./data:/data
      - ./docker:/docker
    working_dir: /data
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: /bin/bash
