services:
  nggasak-analyzer:
    build: .
    container_name: nggasak-analysis
    user: "nggasak"
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: /bin/bash
